// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer.sql

package db

import (
	"context"
	"database/sql"
)

const createCustomer = `-- name: CreateCustomer :one

INSERT INTO customer (customer_id, customer_name, customer_type, city, state, zip_code)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING customer_id, customer_name, customer_type, city, state, zip_code, created_at
`

type CreateCustomerParams struct {
	CustomerID   int32          `json:"customer_id"`
	CustomerName string         `json:"customer_name"`
	CustomerType string         `json:"customer_type"`
	City         sql.NullString `json:"city"`
	State        sql.NullString `json:"state"`
	ZipCode      sql.NullString `json:"zip_code"`
}

// =====================================================
// CUSTOMER QUERIES
// =====================================================
func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, createCustomer,
		arg.CustomerID,
		arg.CustomerName,
		arg.CustomerType,
		arg.City,
		arg.State,
		arg.ZipCode,
	)
	var i Customer
	err := row.Scan(
		&i.CustomerID,
		&i.CustomerName,
		&i.CustomerType,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT customer_id, customer_name, customer_type, city, state, zip_code, created_at FROM customer WHERE customer_id = $1
`

func (q *Queries) GetCustomerByID(ctx context.Context, customerID int32) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByID, customerID)
	var i Customer
	err := row.Scan(
		&i.CustomerID,
		&i.CustomerName,
		&i.CustomerType,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.CreatedAt,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT customer_id, customer_name, customer_type, city, state, zip_code, created_at FROM customer ORDER BY customer_name LIMIT $1 OFFSET $2
`

type ListCustomersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, listCustomers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.CustomerID,
			&i.CustomerName,
			&i.CustomerType,
			&i.City,
			&i.State,
			&i.ZipCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCustomersByName = `-- name: SearchCustomersByName :many
SELECT customer_id, customer_name, customer_type, city, state, zip_code, created_at FROM customer 
WHERE customer_name ILIKE '%' || $1 || '%'
ORDER BY customer_name
LIMIT $2
`

type SearchCustomersByNameParams struct {
	Column1 sql.NullString `json:"column_1"`
	Limit   int32          `json:"limit"`
}

func (q *Queries) SearchCustomersByName(ctx context.Context, arg SearchCustomersByNameParams) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, searchCustomersByName, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.CustomerID,
			&i.CustomerName,
			&i.CustomerType,
			&i.City,
			&i.State,
			&i.ZipCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCustomer = `-- name: UpsertCustomer :one
INSERT INTO customer (customer_id, customer_name, customer_type, city, state, zip_code)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (customer_id) 
DO UPDATE SET 
    customer_name = EXCLUDED.customer_name,
    customer_type = EXCLUDED.customer_type,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip_code = EXCLUDED.zip_code
RETURNING customer_id, customer_name, customer_type, city, state, zip_code, created_at
`

type UpsertCustomerParams struct {
	CustomerID   int32          `json:"customer_id"`
	CustomerName string         `json:"customer_name"`
	CustomerType string         `json:"customer_type"`
	City         sql.NullString `json:"city"`
	State        sql.NullString `json:"state"`
	ZipCode      sql.NullString `json:"zip_code"`
}

func (q *Queries) UpsertCustomer(ctx context.Context, arg UpsertCustomerParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, upsertCustomer,
		arg.CustomerID,
		arg.CustomerName,
		arg.CustomerType,
		arg.City,
		arg.State,
		arg.ZipCode,
	)
	var i Customer
	err := row.Scan(
		&i.CustomerID,
		&i.CustomerName,
		&i.CustomerType,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.CreatedAt,
	)
	return i, err
}
