// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: job_campaigns.sql

package db

import (
	"context"
	"database/sql"
)

const createJobCampaign = `-- name: CreateJobCampaign :one
INSERT INTO job_campaigns (id, name, description, created_at, updated_at)
VALUES (
    $1, 
    $2,
    $3,
    NOW(),
    NOW()
)
RETURNING id, name, description, created_at, updated_at
`

type CreateJobCampaignParams struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateJobCampaign(ctx context.Context, arg CreateJobCampaignParams) (JobCampaign, error) {
	row := q.db.QueryRowContext(ctx, createJobCampaign, arg.ID, arg.Name, arg.Description)
	var i JobCampaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOneJobCampaign = `-- name: GetOneJobCampaign :one
SELECT id, name, description, created_at, updated_at FROM job_campaigns
WHERE job_campaigns.id = $1
`

func (q *Queries) GetOneJobCampaign(ctx context.Context, id int32) (JobCampaign, error) {
	row := q.db.QueryRowContext(ctx, getOneJobCampaign, id)
	var i JobCampaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobCampaigns = `-- name: ListJobCampaigns :many
SELECT id, name, description, created_at, updated_at FROM job_campaigns
ORDER BY job_campaigns.name
`

func (q *Queries) ListJobCampaigns(ctx context.Context) ([]JobCampaign, error) {
	rows, err := q.db.QueryContext(ctx, listJobCampaigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobCampaign
	for rows.Next() {
		var i JobCampaign
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
