// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type BusinessUnit struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type CallCampaign struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type CampaignCategory struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Customer struct {
	ID           int32          `json:"id"`
	Name         string         `json:"name"`
	City         sql.NullString `json:"city"`
	State        sql.NullString `json:"state"`
	Zip          sql.NullString `json:"zip"`
	CustomerType sql.NullString `json:"customer_type"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type Estimate struct {
	ID              int32          `json:"id"`
	Name            string         `json:"name"`
	Description     sql.NullString `json:"description"`
	Subtotal        sql.NullString `json:"subtotal"`
	IsSold          sql.NullBool   `json:"is_sold"`
	SoldBy          uuid.NullUUID  `json:"sold_by"`
	InvoicesID      sql.NullInt32  `json:"invoices_id"`
	OpportunitiesID sql.NullInt32  `json:"opportunities_id"`
	JobsID          sql.NullInt32  `json:"jobs_id"`
	SoldOnDate      sql.NullTime   `json:"sold_on_date"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type Invoice struct {
	ID              int32         `json:"id"`
	CustomersID     int32         `json:"customers_id"`
	JobsID          sql.NullInt32 `json:"jobs_id"`
	EstimatesID     sql.NullInt32 `json:"estimates_id"`
	BusinessUnitsID sql.NullInt32 `json:"business_units_id"`
	IsPaid          sql.NullBool  `json:"is_paid"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
}

type Job struct {
	ID                 int32          `json:"id"`
	JobTypeID          int32          `json:"job_type_id"`
	BusinessUnitID     int32          `json:"business_unit_id"`
	CustomerID         int32          `json:"customer_id"`
	LocationID         int32          `json:"location_id"`
	ProjectID          int32          `json:"project_id"`
	JobCampaignID      int32          `json:"job_campaign_id"`
	CallCampaignID     int32          `json:"call_campaign_id"`
	JobStatus          string         `json:"job_status"`
	JobPriority        string         `json:"job_priority"`
	JobSummary         sql.NullString `json:"job_summary"`
	JobCreationDate    time.Time      `json:"job_creation_date"`
	JobScheduleDate    sql.NullTime   `json:"job_schedule_date"`
	JobCompletionDate  sql.NullTime   `json:"job_completion_date"`
	AssignedTechID     uuid.NullUUID  `json:"assigned_tech_id"`
	SoldTechID         uuid.NullUUID  `json:"sold_tech_id"`
	SoldBuID           sql.NullInt32  `json:"sold_bu_id"`
	CountOfEstimates   sql.NullInt32  `json:"count_of_estimates"`
	SoldEstimateID     sql.NullInt32  `json:"sold_estimate_id"`
	CampaignCategoryID sql.NullInt32  `json:"campaign_category_id"`
	InvoiceID          sql.NullInt32  `json:"invoice_id"`
	OpportunityID      sql.NullInt32  `json:"opportunity_id"`
	IsWarranty         sql.NullBool   `json:"is_warranty"`
	WarrantyOfJobID    sql.NullInt32  `json:"warranty_of_job_id"`
	IsRecall           sql.NullBool   `json:"is_recall"`
	RecallOfJobID      sql.NullInt32  `json:"recall_of_job_id"`
	IsConverted        sql.NullBool   `json:"is_converted"`
	SurveyScore        sql.NullInt32  `json:"survey_score"`
	DispatchedByUserID uuid.NullUUID  `json:"dispatched_by_user_id"`
	BookedByUserID     uuid.NullUUID  `json:"booked_by_user_id"`
	JobIDOfCreatedLead sql.NullInt32  `json:"job_id_of_created_lead"`
	IsZeroCost         sql.NullBool   `json:"is_zero_cost"`
	ScheduledTime      sql.NullTime   `json:"scheduled_time"`
	FirstDispatch      sql.NullTime   `json:"first_dispatch"`
	HoldDate           sql.NullTime   `json:"hold_date"`
	SoldDate           sql.NullTime   `json:"sold_date"`
	StartTime          sql.NullTime   `json:"start_time"`
	EndTime            sql.NullTime   `json:"end_time"`
	PrimaryTechID      uuid.NullUUID  `json:"primary_tech_id"`
	FirstResponseTime  sql.NullInt32  `json:"first_response_time"`
}

type JobCampaign struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type JobSkill struct {
	ID             int32          `json:"id"`
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	BusinessUnitID sql.NullInt32  `json:"business_unit_id"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type JobType struct {
	ID             int32          `json:"id"`
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	BusinessUnitID sql.NullInt32  `json:"business_unit_id"`
	SkillsID       sql.NullInt32  `json:"skills_id"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type Location struct {
	ID         int32          `json:"id"`
	Name       string         `json:"name"`
	City       sql.NullString `json:"city"`
	State      sql.NullString `json:"state"`
	Zip        sql.NullString `json:"zip"`
	CustomerID int32          `json:"customer_id"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type Opportunity struct {
	ID              int32         `json:"id"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
	BusinessUnitsID sql.NullInt32 `json:"business_units_id"`
	JobTypesID      sql.NullInt32 `json:"job_types_id"`
	TechniciansID   uuid.NullUUID `json:"technicians_id"`
	JobsID          sql.NullInt32 `json:"jobs_id"`
}

type Project struct {
	ID        int32          `json:"id"`
	Summary   sql.NullString `json:"summary"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type Technician struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Email       string         `json:"email"`
	PhoneNumber sql.NullString `json:"phone_number"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type User struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Email       string         `json:"email"`
	PhoneNumber sql.NullString `json:"phone_number"`
	IsTech      sql.NullBool   `json:"is_tech"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}
