// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project.sql

package db

import (
	"context"
	"database/sql"
)

const createProject = `-- name: CreateProject :one

INSERT INTO project (project_name)
VALUES ($1)
RETURNING project_id, project_name, created_at
`

// =====================================================
// PROJECT QUERIES
// =====================================================
func (q *Queries) CreateProject(ctx context.Context, projectName sql.NullString) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, projectName)
	var i Project
	err := row.Scan(&i.ProjectID, &i.ProjectName, &i.CreatedAt)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT project_id, project_name, created_at FROM project WHERE project_id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, projectID int32) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, projectID)
	var i Project
	err := row.Scan(&i.ProjectID, &i.ProjectName, &i.CreatedAt)
	return i, err
}
