-- +goose Up
CREATE TABLE jobs (
    id INT PRIMARY KEY NOT NULL,
    job_type_id INT NOT NULL,
    business_unit_id INT NOT NULL,
    customer_id INT NOT NULL,
    location_id INT NOT NULL,
    project_id INT NOT NULL,
    job_campaign_id INT NOT NULL,
    call_campaign_id INT NOT NULL,
    job_status TEXT NOT NULL,
    job_priority TEXT NOT NULL,
    job_summary TEXT,
    job_creation_date TIMESTAMP NOT NULL,
    job_schedule_date TIMESTAMP,
    job_completion_date TIMESTAMP,
    assigned_tech_id UUID,
    sold_tech_id UUID,
    sold_bu_id INT,
    count_of_estimates INT,
    sold_estimate_id INT,
    campaign_category_id INT,
    invoice_id INT,
    opportunity_id INT,
    is_warranty BOOLEAN, 
    warranty_of_job_id INT,
    is_recall BOOLEAN,
    recall_of_job_id INT,
    is_converted BOOLEAN,
    survey_score INT,
    dispatched_by_user_id UUID,
    booked_by_user_id UUID,
    job_id_of_created_lead INT,
    is_zero_cost BOOLEAN,
    scheduled_time TIMESTAMP,
    first_dispatch TIMESTAMP,
    hold_date TIMESTAMP,
    sold_date TIMESTAMP,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    primary_tech_id UUID,
    first_response_time INT,
    FOREIGN KEY (job_type_id) REFERENCES job_types(id),
    FOREIGN KEY (business_unit_id) REFERENCES business_units(id),
    FOREIGN KEY (customer_id) REFERENCES customers(id),
    FOREIGN KEY (location_id) REFERENCES locations(id),
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (job_campaign_id) REFERENCES job_campaigns(id),
    FOREIGN KEY (call_campaign_id) REFERENCES call_campaigns(id),
    FOREIGN KEY (assigned_tech_id) REFERENCES technicians(id),
    FOREIGN KEY (sold_tech_id) REFERENCES technicians(id),
    FOREIGN KEY (sold_bu_id) REFERENCES business_units(id),
    FOREIGN KEY (sold_estimate_id) REFERENCES estimates(id),
    FOREIGN KEY (campaign_category_id) REFERENCES campaign_categories(id),
    FOREIGN KEY (invoice_id) REFERENCES invoices(id),
    FOREIGN KEY (opportunity_id) REFERENCES opportunities(id),
    FOREIGN KEY (dispatched_by_user_id) REFERENCES users(id),
    FOREIGN KEY (booked_by_user_id) REFERENCES users(id),
    FOREIGN KEY (primary_tech_id) REFERENCES technicians(id),
    FOREIGN KEY (warranty_of_job_id) REFERENCES jobs(id),
    FOREIGN KEY (recall_of_job_id) REFERENCES jobs(id),
    FOREIGN KEY (job_id_of_created_lead) REFERENCES jobs(id)
);

-- +goose Down
DROP TABLE jobs;